version: '3.5'

services:
    front-end:
      build: 
        context: ./frontend
        args: 
          react_app_backend_url: http://localhost:8080
      ports: 
        - 5000:5000
      container_name: front-end
    back-end:
      build: 
        context: ./backend
        args: 
          postgres_host: postgres
          request_origin: http://localhost:5000
          redis_host: redis
      ports: 
        - 8080:8080
      container_name: back-end
    redis:
      image: redis
      ports:
        - 6379:6379
      container_name: redis-backend
    postgres:
      image: postgres:13.2-alpine
      restart: unless-stopped
      environment:
        POSTGRES_PASSWORD: postgres
      container_name: postgres-backend
    nginx: 
      image: nginx:1.19-alpine
      ports:
      - 80:80
      volumes:
        - "./nginx.conf:/etc/nginx/nginx.conf"
      depends_on:
       - front-end
       - back-end
